spring:
  application:
    name: order
  cloud:
    stream:
      bindings:
        myInput:
          group: order
          content-type: application/json
          destination: mytestOrder
        myOutput:
          destination: mytestOrder
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
  zipkin:
    base-url: http://192.168.99.100:9411/zipkin/
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.99.100
    port: 6379
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
    getProductInfoList:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    create:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
feign:
  hystrix:
    enabled: true
env:
  dev
logging:
  level:
    org.springframework.cloud.openfeign: debug
